DesignerWebsite/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.core.mail import send_mail
from django.shortcuts import render
from designers.models import Designers,Rawpass
from django.core.files.storage import FileSystemStorage
from designers.forms import SendMail
from django.core.mail import send_mail
from django.conf import settings
from gbstore.models import *
from rest_framework import routers
from apis import views
from rest_framework.urlpatterns import format_suffix_patterns
from datetime import datetime,date
from gbstore.forms import ProductAdd,PlywoodAddForm,LaminatesAddForm,AdhesiveAdd
import random
import string
from django.contrib.auth.hashers import make_password
from merchant.forms import MerchantAddForm,SGForm,merchantSearch
from merchant.models import *
from designers.models import Designers



def Mail(request):
    email=""
    if request.method == "POST":
        MyRegisterForm = SendMail(request.POST)
        if MyRegisterForm.is_valid():
            Send_To=MyRegisterForm.cleaned_data['Send_To']
            dbuser = Designers.objects.filter(email=Send_To)
            if dbuser:
                user=dbuser[0]
                randpass=''.join(random.choice(string.ascii_uppercase+string.digits) for _ in range(8))
                dbuser[0].password=make_password(randpass)
                dbuser[0].designerID='GBIDX0{0}'.format(Designers.objects.count())
                rawpass=Rawpass(rawpass=randpass,designer=dbuser[0])
                rawpass.save()
                dbuser[0].save()
                contact_message =  'Your DesignerId is {0} and password is  {1} '.format(user.designerID,randpass)
                from_email = settings.EMAIL_HOST_USER
                to_email = []
                to_email.append(Send_To)
                send_mail('Registration Succesfull', contact_message, from_email, to_email, fail_silently=False)



        else:
            MyRegisterForm = SendMail(request.GET)

    return render(request, 'designers/SendMails.html',{})

def product_add(request):
    errors=""

    if request.method=='POST':
        myform=ProductAdd(request.POST,request.FILES)

        if myform.is_valid():
            p=Products()
            count=Products.objects.count()+1
            p.gbcode='GBPRO0{0}'.format(count)
            if myform.cleaned_data['comp_code']:
                p.comp_code = myform.cleaned_data['comp_code']
            else:
                p.comp_code=p.gbcode

            p.name=myform.cleaned_data['name']
            p.company=myform.cleaned_data['company']
            p.address=myform.cleaned_data['address']
            if myform.cleaned_data['description']:
              p.description=myform.cleaned_data['description']
            if myform.cleaned_data['colour']:
                p.colour=myform.cleaned_data['colour']
            if myform.cleaned_data['length']:
                p.length=myform.cleaned_data['length']
            if myform.cleaned_data['height']:
                p.height=myform.cleaned_data['height']
            if myform.cleaned_data['radius']:
                p.radius=myform.cleaned_data['radius']
            p.image1=myform.cleaned_data['image1']
            if myform.cleaned_data['image2']:
                p.image2=myform.cleaned_data['image2']
            p.original_price=myform.cleaned_data['original_price']
            p.cost_price=myform.cleaned_data['cost_price']
            p.selling_price=myform.cleaned_data['selling_price']
            p.profit=((p.selling_price-p.cost_price)/p.cost_price)*100
            if myform.cleaned_data['star']:
                p.star=True
            else:
                p.star=False
            p.date=datetime.now()
            p.save()
            context = {'errors': errors}
            return render(request, 'gbstore/product_add.html', context=context)


        else:
            print(myform.errors)
            errors="Not Inserted"
    context = {'errors': errors}
    return render(request,'gbstore/product_add.html',context=context)

def product_search(request):


    products=list(Products.objects.filter(star=True).order_by('-date')[:10])
    nonstar=Products.objects.filter(star=False).order_by('date')[:20]
    for x in nonstar:
        products.append(x)
    random.shuffle(products)
    new=Products.objects.filter(new=True).order_by('date')[:10]
    if request.method=='POST':
        products=[]
        products=list(Products.objects.filter(name__contains=request.POST['search']).order_by('date'))
        products.extend(list(Products.objects.filter(company__contains=request.POST['search']).order_by('date')))
        products.extend(list(Products.objects.filter(description__contains=request.POST['search']).order_by('date')))
        new=[]
    context={
        'products':products,
        'new':new,
    }
    return render(request, 'gbstore/product_search.html', context=context)

def product_update(request):
    errors = ""
    context = {'errors': errors}
    return render(request, 'gbstore/product_add.html', context=context)


def plywood_add(request):
    if request.method=='POST':

        myform=PlywoodAddForm(request.POST,request.FILES)
        print(request.POST.getlist('vendor'))
        if myform.is_valid():
            ply=Plywood()
            ply.brand = myform.cleaned_data['brand']
            ply.dimention = myform.cleaned_data['dimention']
            ply.Thickness = myform.cleaned_data['Thickness']
            ply.series = myform.cleaned_data['series']
            if myform.cleaned_data['img1']:
                ply.img1 = myform.cleaned_data['img1']
            if myform.cleaned_data['img2']:
                ply.img2 = myform.cleaned_data['img2']
            if myform.cleaned_data['compcode']:
                ply.compcode = myform.cleaned_data['compcode']
            if myform.cleaned_data['description']:
                ply.description = myform.cleaned_data['description']
            ply.original_price = myform.cleaned_data['original_price']
            ply.cost_price = myform.cleaned_data['cost_price']
            ply.selling_price = myform.cleaned_data['selling_price']
            ply.date=datetime.now()
            code=Plywood.objects.count()+1
            ply.gbcode='GBPLY0{0}'.format(code)
            gbcode=ply.gbcode
            ply.save()
            for x in request.POST.getlist('vendor'):

                if Merchants.objects.filter(merchantID=x):
                    merch=Mercentdise()
                    merch.type="Plywood"
                    merch.merchant=Merchants.objects.get(merchantID=x)
                    merch.gbcode=gbcode
                    merch.save()
            br=Brand.objects.filter(name=ply.brand,typ='Plywood')
            if not br:
                br1=Brand()
                br1.name=ply.brand
                br1.typ='Plywood'
                br1.save()
            dim = Dimention.objects.filter(name=ply.dimention, typ='Plywood')
            if not dim:
                dim1 = Dimention()
                dim1.name = ply.dimention
                dim1.typ = 'Plywood'
                dim1.save()
            thik=Thickness.objects.filter(name=ply.Thickness,typ='Plywood')
            if not thik:
                thik1 = Thickness()
                thik1.name = ply.Thickness
                thik1.typ = 'Plywood'
                thik1.save()
    vendor = list(Merchants.objects.all())

    content={

        'merchants':vendor
    }
    return render(request,'gbstore/plywood_add.html',content)


def laminates_add(request):
    if request.method=='POST':
        myform=LaminatesAddForm(request.POST,request.FILES)
        if myform.is_valid():
            ply=Laminates()
            ply.brand = myform.cleaned_data['brand']
            ply.dimention = myform.cleaned_data['dimention']
            ply.Thickness = myform.cleaned_data['Thickness']
            ply.series = myform.cleaned_data['series']
            if myform.cleaned_data['img1']:
                ply.img1 = myform.cleaned_data['img1']
            if myform.cleaned_data['img2']:
                ply.img2 = myform.cleaned_data['img2']
            if myform.cleaned_data['compcode']:
                ply.compcode = myform.cleaned_data['compcode']
            if myform.cleaned_data['description']:
                ply.description = myform.cleaned_data['description']
            ply.original_price = myform.cleaned_data['original_price']
            ply.cost_price = myform.cleaned_data['cost_price']
            ply.selling_price = myform.cleaned_data['selling_price']
            ply.date=datetime.now()
            code=Laminates.objects.count()+1
            ply.gbcode='GBLAM0{0}'.format(code)
            ply.dim = myform.cleaned_data['dim']
            ply.finish = myform.cleaned_data['finish']
            ply.save()
            for x in request.POST.getlist('vendor'):

                if Merchants.objects.filter(merchantID=x):
                    merch=Mercentdise()
                    merch.type="Laminates"
                    merch.merchant=Merchants.objects.get(merchantID=x)
                    merch.gbcode=ply.gbcode
                    merch.save()
            br = Brand.objects.filter(name=ply.brand, typ='Laminates')
            if not br:
                br1 = Brand()
                br1.name = ply.brand
                br1.typ = 'Laminates'
                br1.save()
            dim = Dimention.objects.filter(name=ply.dimention, typ='Laminates')
            if not dim:
                dim1 = Dimention()
                dim1.name = ply.dimention
                dim1.typ = 'Laminates'
                dim1.save()
            thik = Thickness.objects.filter(name=ply.Thickness, typ='Laminates')
            if not thik:
                thik1 = Thickness()
                thik1.name = ply.Thickness
                thik1.typ = 'Laminates'
                thik1.save()

apis/urls.py
from django.conf.urls import url
from functools import wraps
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name='apis'


def csrf_exempt(view_func):
    def wrapped_view(request,*args,**kwargs):
        return view_func(request,*args,**kwargs)
    wrapped_view.csrf_exempt=True
    return wraps(view_func,)(wrapped_view)


urlpatterns = format_suffix_patterns( [
    url(r'^hu/$', views.IndexViewSet.as_view()),
    url(r'^humi/$', csrf_exempt(views.Login.as_view())),
    url(r'^humis/$', csrf_exempt(views.SearchBlogs.as_view())),
    url(r'^ru/$', csrf_exempt(views.CreateBlog.as_view())),
    url(r'^rumi/$', csrf_exempt(views.DesignerBlogs.as_view())),
    url(r'^rumis/$', csrf_exempt(views.LikeView.as_view())),
    url(r'^sayonara/$', csrf_exempt(views.Logout.as_view())),



    #url(r'^sl/$', csrf_exempt(views.StoreLogin.as_view())),
])

store/urls.py
from django.conf.urls import url

from . import views

app_name = 'store'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^getverified/$', views.getverified, name='getverified'),
    url(r'^notverified/$', views.notverified, name='notverified'),
    url(r'^verification/$', views.verification, name='verification'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^myprofile/$', views.myprofile, name='myprofile'),
    url(r'^searchres/$', views.searchres, name='searchres'),
    url(r'^ajaxsearch/$', views.ajaxsearch, name='ajaxsearch'),
    url(r'^products/(?P<product_name>[ \t\n\r\f\vA-Za-z]+)/$', views.products, name='products'),
    url(r'^addtocart/$', views.add_to_cart, name='addtocart'),
    url(r'^cart/$', views.view_cart, name='viewcart'),
    url(r'^delitem/$', views.del_item, name='delitem'),
    url(r'^updateitem/$', views.update_item, name='updateitem'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^delcart/$', views.delcart, name='delcart'),
]

store/models.py
from django.db import models

from designers.models import Designers
from seller.models import Sellers


class VerifiedDesigners(models.Model):
    id = models.AutoField(primary_key=True)
    designer = models.OneToOneField(Designers, on_delete=models.CASCADE)
    verified = models.BooleanField(default=False)
    document = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.designer.name + ' ' + str(self.verified)


class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.name


class Products(models.Model):
    productID = models.CharField(max_length=15)
    name = models.CharField(max_length=40, null=True)
    company = models.CharField(max_length=40, null=True)
    price =  models.DecimalField(max_digits=8, decimal_places=2, null=True)
    availability = models.BooleanField(default=True)
    seller = models.ForeignKey(Sellers, null=True, blank=True, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name + ' ' + self.company


class Bills(models.Model):
    billID = models.CharField(max_length=15)
    designer = models.ForeignKey(Designers, null=True, blank=True, on_delete=models.CASCADE)
    transactionID = models.CharField(max_length=15)
    totalPrice = models.DecimalField(max_digits=8, decimal_places=2)
    discount = models.DecimalField(max_digits=8, decimal_places=2)
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return self.billID + ' ' + self.designer.name + ' ' + self.transactionID


class ShippingAddress(models.Model):
    designer = models.ForeignKey(Designers, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=True)
    firmname = models.CharField(max_length=50, null=True)
    number = models.PositiveIntegerField(null=True)
    city = models.CharField(max_length=30, null=True)
    state = models.CharField(max_length=30, null=True)
    address = models.CharField(max_length=500, null=True)
    pincode = models.PositiveIntegerField(null=True)

    def __str__(self):
        return self.name + ' ' + self.firmname + ' ' + self.pincode


class Purchases(models.Model):
    designer = models.ForeignKey(Designers, null=True, blank=True, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, null=True, blank=True, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    totalPrice = models.DecimalField(max_digits=8, decimal_places=2)
    discount = models.DecimalField(max_digits=8, decimal_places=2)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    seller = models.ForeignKey(Sellers, null=True, blank=True, on_delete=models.CASCADE)
    bill = models.ForeignKey(Bills, null=True, blank=True, on_delete=models.CASCADE)
    shippingAddress = models.ForeignKey(ShippingAddress, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.designer.name + ' ' + self.product.name + ' ' + self.quantity + ' ' + self.seller.name + ' ' + self.amount

store/forms.py
from django import forms

from designers.models import Designers


class StoreLoginForm(forms.Form):
    designerID = forms.CharField(max_length=15)
    password = forms.CharField(widget=forms.PasswordInput())


class VerificationForm(forms.Form):
    verificationImage = forms.ImageField()

    def __init__(self, *args, **kwargs):
        super(VerificationForm, self).__init__(*args, **kwargs)
        self.fields['verificationImage'].required = False


class SearchForm(forms.Form):
    select = forms.CharField()
    search = forms.CharField()


class AddressForm(forms.Form):
    name = forms.CharField()
    firmname = forms.CharField()
    number = forms.IntegerField
    email = forms.EmailField()
    city = forms.CharField()
    state = forms.CharField()
    address = forms.CharField()
    pincode = forms.IntegerField()

store/templates/store/addaddress.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Add Address</title>
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap-theme.min.css' %}">
</head>
<body>
    <h1>Add Address</h1>
    <form class="form-horizontal" action="{% url 'store:checkout' %}" method="post">
        <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" class="form-control" placeholder="Name">
        </div>
        <div class="form-group">
            <label class="control-label">Firm Name</label>
            <input type="text" class="form-control" placeholder="Firm Name">
        </div>
        <div class="form-group">
            <label class="control-label">Phone Number</label>
            <input type="number" class="form-control" placeholder="Name">
        </div>
        <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" class="form-control" placeholder="Name">
        </div>
        <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" class="form-control" placeholder="Name">
        </div>
        <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" class="form-control" placeholder="Name">
        </div>
        <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" class="form-control" placeholder="Name">
        </div>
        <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" class="form-control" placeholder="Name">
        </div>
    </form>

    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
</body>
</html>

store/templates/store/ajax_search.html
<p>hello</p>
{% if filter.count > 0 %}


{% for  product in filter %}
  <li>{{product.name}}</li>
{% endfor %}

{% endif %}

store/templates/store/cart.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Cart</title>

    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap-select/dist/css/bootstrap-select.min.css' %}">

</head>
<body>

    {% for qty, product in products.items %}
    <div>
        Name: {{ product.name }} <br>
        Quantity: <input type="number" id="{{ product.id }}" value="{{ qty }}"> <br>
        <button class="btn btn-danger" value="{{ product.id }}">Delete</button>
    </div><br><br>
    {% endfor %}
    <br>
    <a class="btn btn-success" href="{% url 'store:checkout' %}">Checkout Cart</a>

    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'store/js/cart.js' %}"></script>
</body>
</html>

store/templates/store/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Checkout</title>
</head>
<body>

</body>
</html>

store/templates/store/dashboard.html
<!DOCTYPE html>
<html lang="en">

{% load staticfiles %}

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Ghar Banao Store</title>

    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap-select/dist/css/bootstrap-select.min.css' %}">

</head>

<body>

    {% if dbuser %}


    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Brand</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-collapse-1">

                <form class="navbar-form navbar-left" action="{% url 'store:searchres' %}" method="get">{% csrf_token %}
                    <div class="input-group">
                        <div class="input-group-btn">
                            <select class="selectpicker" id="select" name="select" style="display: none;">
                                <option>All Categories</option>
                                {% for category in categories %}
                                <option>{{category.name}}</option>
                                {% endfor %}
                            </select>
                        </div><!-- /btn-group -->
                        <input type="text" autocomplete="off" class="form-control" id="search" placeholder="Search for products" name="search">

                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                        </span>
                    </div>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Request Items</a></li>
                    <li><a href="#">Track Orders</a></li>
                    <li><a href="{% url 'store:viewcart' %}">Cart ({{ cartcount }})</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{dbuser.name}}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">My Orders</a></li>
                            <li><a href="#">My Transactions</a></li>
                            <li><a href="#">My Lists</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">My Requests</a></li>
                            <li><a href="#">Recommendations</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'store:myprofile' %}">My Account</a></li>
                            <li><a href="{% url 'store:logout' %}">Sign Out</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div>
        <ul id="ajaxsearch"></ul>
    </div>

    {% endif %}

    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'store/js/ajax.js' %}"></script>

</body>
</html>

store/templates/store/getverified.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
    
    <head>
    
        <meta charset="UTF-8">
    
        <title>Ghar Banao Store</title>
    
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    
    </head>
    
    <body>
        <h1>Get Verified</h1>
        <form name="form" action="{% url 'store:verification' %}" method="post" enctype="multipart/form-data"> {% csrf_token %}
            <div>
                <p>Upload:</p>
                <input type="file" name="verificationImage" />
            </div>
            <div>
                <button type="submit" value="Submit">Submit</button>
            </div>
        </form>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
    </body>

</html>

store/templates/store/myprofile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Profile</title>
</head>
<body>
    {% if dbuser %}
        {{ dbuser.name }} <br>
        {% if vdes %}
            {{ vdes.verified }}
        {% endif %}
    {% endif %}
</body>
</html>

store/templates/store/notverified.html
<!DOCTYPE html>
<html lang="en">

{% load staticfiles %}

<head>
    <title>Login Error</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'store/css/notverified.css' %}">
</head>
<body>
    <center>
        <div id="window" align="">
            <img src="{% static 'store/img/error.png' %}">
            {% if dbuser %}

            <p>DesignerID <span> {{ dbuser.designerID }} </span> is not verified to use GharBanao Store yet.<br> Click continue to go to the verification page.</p>
            <a id="continue" href="{% url 'store:getverified' %}">continue</a>

            {% endif %}
        </div>
    </center>

</body>
</html>

store/templates/store/search.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Search Results</title>
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap-select/dist/css/bootstrap-select.min.css' %}">
</head>
<body>
    <br><br><br><br><br><br>
    <ul>

        {% for product in filter %}

        <li><a href="{% url 'store:products' product.name %}"> {{ product.name }}</a></li>

        {% endfor %}
    </ul>

    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>
</body>
</html>

store/templates/store/verification.html
<!DOCTYPE html>
<html lang="en">

{% load staticfiles %}

<head>
    <title>Login Error</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'store/css/verification.css' %}">
</head>
<body>
    <center>
        <div id="window" align="">
            <img src="{% static 'store/img/verified.png' %}">

            <p>Congratulations! You have successfully verified with DesignerID <span> ### </span>.<br> Click continue to go to GharBanao Store.</p>
            <a id="continue" href="#">continue</a>

        </div>
    </center>

</body>
</html>