DesignerWebsite/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.core.mail import send_mail
from django.shortcuts import render
from designers.models import Designers,Rawpass
from django.core.files.storage import FileSystemStorage
from designers.forms import SendMail
from django.core.mail import send_mail
from django.conf import settings
from gbstore.models import *
from rest_framework import routers
from apis import views
from rest_framework.urlpatterns import format_suffix_patterns
from datetime import datetime,date
from gbstore.forms import ProductAdd,PlywoodAddForm,LaminatesAddForm,AdhesiveAdd
import random
import string
from django.contrib.auth.hashers import make_password
from merchant.forms import MerchantAddForm,SGForm,merchantSearch
from merchant.models import *
from designers.models import Designers



def Mail(request):
    email=""
    if request.method == "POST":
        MyRegisterForm = SendMail(request.POST)
        if MyRegisterForm.is_valid():
            Send_To=MyRegisterForm.cleaned_data['Send_To']
            dbuser = Designers.objects.filter(email=Send_To)
            if dbuser:
                user=dbuser[0]
                randpass=''.join(random.choice(string.ascii_uppercase+string.digits) for _ in range(8))
                dbuser[0].password=make_password(randpass)
                dbuser[0].designerID='GBIDX0{0}'.format(Designers.objects.count())
                rawpass=Rawpass(rawpass=randpass,designer=dbuser[0])
                rawpass.save()
                dbuser[0].save()
                contact_message =  'Your DesignerId is {0} and password is  {1} '.format(user.designerID,randpass)
                from_email = settings.EMAIL_HOST_USER
                to_email = []
                to_email.append(Send_To)
                send_mail('Registration Succesfull', contact_message, from_email, to_email, fail_silently=False)



        else:
            MyRegisterForm = SendMail(request.GET)

    return render(request, 'designers/SendMails.html',{})

def product_add(request):
    errors=""

    if request.method=='POST':
        myform=ProductAdd(request.POST,request.FILES)

        if myform.is_valid():
            p=Products()
            count=Products.objects.count()+1
            p.gbcode='GBPRO0{0}'.format(count)
            if myform.cleaned_data['comp_code']:
                p.comp_code = myform.cleaned_data['comp_code']
            else:
                p.comp_code=p.gbcode

            p.name=myform.cleaned_data['name']
            p.company=myform.cleaned_data['company']
            p.address=myform.cleaned_data['address']
            if myform.cleaned_data['description']:
              p.description=myform.cleaned_data['description']
            if myform.cleaned_data['colour']:
                p.colour=myform.cleaned_data['colour']
            if myform.cleaned_data['length']:
                p.length=myform.cleaned_data['length']
            if myform.cleaned_data['height']:
                p.height=myform.cleaned_data['height']
            if myform.cleaned_data['radius']:
                p.radius=myform.cleaned_data['radius']
            p.image1=myform.cleaned_data['image1']
            if myform.cleaned_data['image2']:
                p.image2=myform.cleaned_data['image2']
            p.original_price=myform.cleaned_data['original_price']
            p.cost_price=myform.cleaned_data['cost_price']
            p.selling_price=myform.cleaned_data['selling_price']
            p.profit=((p.selling_price-p.cost_price)/p.cost_price)*100
            if myform.cleaned_data['star']:
                p.star=True
            else:
                p.star=False
            p.date=datetime.now()
            p.save()
            context = {'errors': errors}
            return render(request, 'gbstore/product_add.html', context=context)


        else:
            print(myform.errors)
            errors="Not Inserted"
    context = {'errors': errors}
    return render(request,'gbstore/product_add.html',context=context)

def product_search(request):


    products=list(Products.objects.filter(star=True).order_by('-date')[:10])
    nonstar=Products.objects.filter(star=False).order_by('date')[:20]
    for x in nonstar:
        products.append(x)
    random.shuffle(products)
    new=Products.objects.filter(new=True).order_by('date')[:10]
    if request.method=='POST':
        products=[]
        products=list(Products.objects.filter(name__contains=request.POST['search']).order_by('date'))
        products.extend(list(Products.objects.filter(company__contains=request.POST['search']).order_by('date')))
        products.extend(list(Products.objects.filter(description__contains=request.POST['search']).order_by('date')))
        new=[]
    context={
        'products':products,
        'new':new,
    }
    return render(request, 'gbstore/product_search.html', context=context)

def product_update(request):
    errors = ""
    context = {'errors': errors}
    return render(request, 'gbstore/product_add.html', context=context)


def plywood_add(request):
    if request.method=='POST':

        myform=PlywoodAddForm(request.POST,request.FILES)
        print(request.POST.getlist('vendor'))
        if myform.is_valid():
            ply=Plywood()
            ply.brand = myform.cleaned_data['brand']
            ply.dimention = myform.cleaned_data['dimention']
            ply.Thickness = myform.cleaned_data['Thickness']
            ply.series = myform.cleaned_data['series']
            if myform.cleaned_data['img1']:
                ply.img1 = myform.cleaned_data['img1']
            if myform.cleaned_data['img2']:
                ply.img2 = myform.cleaned_data['img2']
            if myform.cleaned_data['compcode']:
                ply.compcode = myform.cleaned_data['compcode']
            if myform.cleaned_data['description']:
                ply.description = myform.cleaned_data['description']
            ply.original_price = myform.cleaned_data['original_price']
            ply.cost_price = myform.cleaned_data['cost_price']
            ply.selling_price = myform.cleaned_data['selling_price']
            ply.date=datetime.now()
            code=Plywood.objects.count()+1
            ply.gbcode='GBPLY0{0}'.format(code)
            gbcode=ply.gbcode
            ply.save()
            for x in request.POST.getlist('vendor'):

                if Merchants.objects.filter(merchantID=x):
                    merch=Mercentdise()
                    merch.type="Plywood"
                    merch.merchant=Merchants.objects.get(merchantID=x)
                    merch.gbcode=gbcode
                    merch.save()
            br=Brand.objects.filter(name=ply.brand,typ='Plywood')
            if not br:
                br1=Brand()
                br1.name=ply.brand
                br1.typ='Plywood'
                br1.save()
            dim = Dimention.objects.filter(name=ply.dimention, typ='Plywood')
            if not dim:
                dim1 = Dimention()
                dim1.name = ply.dimention
                dim1.typ = 'Plywood'
                dim1.save()
            thik=Thickness.objects.filter(name=ply.Thickness,typ='Plywood')
            if not thik:
                thik1 = Thickness()
                thik1.name = ply.Thickness
                thik1.typ = 'Plywood'
                thik1.save()
    vendor = list(Merchants.objects.all())

    content={

        'merchants':vendor
    }
    return render(request,'gbstore/plywood_add.html',content)


def laminates_add(request):
    if request.method=='POST':
        myform=LaminatesAddForm(request.POST,request.FILES)
        if myform.is_valid():
            ply=Laminates()
            ply.brand = myform.cleaned_data['brand']
            ply.dimention = myform.cleaned_data['dimention']
            ply.Thickness = myform.cleaned_data['Thickness']
            ply.series = myform.cleaned_data['series']
            if myform.cleaned_data['img1']:
                ply.img1 = myform.cleaned_data['img1']
            if myform.cleaned_data['img2']:
                ply.img2 = myform.cleaned_data['img2']
            if myform.cleaned_data['compcode']:
                ply.compcode = myform.cleaned_data['compcode']
            if myform.cleaned_data['description']:
                ply.description = myform.cleaned_data['description']
            ply.original_price = myform.cleaned_data['original_price']
            ply.cost_price = myform.cleaned_data['cost_price']
            ply.selling_price = myform.cleaned_data['selling_price']
            ply.date=datetime.now()
            code=Laminates.objects.count()+1
            ply.gbcode='GBLAM0{0}'.format(code)
            ply.dim = myform.cleaned_data['dim']
            ply.finish = myform.cleaned_data['finish']
            ply.save()
            for x in request.POST.getlist('vendor'):

                if Merchants.objects.filter(merchantID=x):
                    merch=Mercentdise()
                    merch.type="Laminates"
                    merch.merchant=Merchants.objects.get(merchantID=x)
                    merch.gbcode=ply.gbcode
                    merch.save()
            br = Brand.objects.filter(name=ply.brand, typ='Laminates')
            if not br:
                br1 = Brand()
                br1.name = ply.brand
                br1.typ = 'Laminates'
                br1.save()
            dim = Dimention.objects.filter(name=ply.dimention, typ='Laminates')
            if not dim:
                dim1 = Dimention()
                dim1.name = ply.dimention
                dim1.typ = 'Laminates'
                dim1.save()
            thik = Thickness.objects.filter(name=ply.Thickness, typ='Laminates')
            if not thik:
                thik1 = Thickness()
                thik1.name = ply.Thickness
                thik1.typ = 'Laminates'
                thik1.save()

apis/urls.py
from django.conf.urls import url
from functools import wraps
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name='apis'


def csrf_exempt(view_func):
    def wrapped_view(request,*args,**kwargs):
        return view_func(request,*args,**kwargs)
    wrapped_view.csrf_exempt=True
    return wraps(view_func,)(wrapped_view)


urlpatterns = format_suffix_patterns( [
    url(r'^hu/$', views.IndexViewSet.as_view()),
    url(r'^humi/$', csrf_exempt(views.Login.as_view())),
    url(r'^humis/$', csrf_exempt(views.SearchBlogs.as_view())),
    url(r'^ru/$', csrf_exempt(views.CreateBlog.as_view())),
    url(r'^rumi/$', csrf_exempt(views.DesignerBlogs.as_view())),
    url(r'^rumis/$', csrf_exempt(views.LikeView.as_view())),
    url(r'^sayonara/$', csrf_exempt(views.Logout.as_view())),



    #url(r'^sl/$', csrf_exempt(views.StoreLogin.as_view())),
])

designers/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views

app_name='designers'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'register/$', views.DesignerCreate.as_view(), name='register'),
    url(r'login/$', views.login, name='login'),
    url(r'dashboard/$', views.registeration, name='registeration'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'registerconf/$', views.regcon, name='regcon'),
    url(r'our_designers', views.designersview, name='ourDes'),
    url(r'change_password/$', views.change_password, name='password_change'),
    url(r'wrong_password/$', views.wrongPassword, name='wrongPassword'),
    url(r'create_blog/$', views.blog, name='blog'),
    url(r'view_blogs/$',views.blog_search,name='blogsearch'),
    url(r'^(?P<status>[0-9]+)/$',views.next,name='next'),
    url(r'^dp_change/$',views.edit_dp,name='edit_dp'),
    url(r'^address_change/$',views.edit_address,name='edit_address'),
    url(r'^about_change/$',views.edit_about,name='edit_about'),
    url(r'^jobs/$',views.myjobs,name='myjobs'),
    url(r'^editjob/$',views.editjob,name='editjob'),
    url(r'^update/$',views.update,name='update'),
    url(r'^requestitem',views.requestitem,name='requestitem'),
    #url(r'^design/$', views.designs, name='design'),
    url(r'^login1/$', views.login1, name='login1'),
    url(r'^logout1/$', views.logout1, name='logout1'),
    url(r'^edit_des/$',views.edit_designs,name='edit_designs'),
    url(r'^forgotpass/$', views.forgotpass, name='fp'),
    url(r'^forgotpass/update/$', views.passmatch, name='fpu'),
    url(r'^resendotp/$', views.resendotp, name='reotp'),
    url(r'^test/$', views.test, name='test'),



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

designers/forms.py
from django import forms

from .models import Designers

class DesignerDetails(forms.Form):
    designerID = forms.CharField(max_length=15)
    password = forms.CharField(widget=forms.PasswordInput())

    def clean_message(self):
        print("Hello")
        designerID=self.cleaned_data.get("designerID")
        password=self.cleaned_data("password")
        dbuser=Designers.objects.filter(designerID=designerID)
        if not dbuser:
            raise forms.ValidationError("User does not exist in our db!")
        return designerID

class SendMail(forms.Form):
    Send_To=forms.CharField(max_length=30)


class PortfolioDetails(forms.Form):
    AboutMe = forms.CharField(max_length=200)
    AboutYourDesigns = forms.CharField(max_length=300)
    design2 = forms.ImageField()
    design3 = forms.ImageField()

    def __init__(self, *args, **kwargs):
        super(PortfolioDetails, self).__init__(*args, **kwargs)
        self.fields['design2'].required = False
        self.fields['design3'].required=False

    def clean_message(self):
        cleaned_data=super(PortfolioDetails, self).clean()
        AboutMe=cleaned_data.get("AboutMe")
        AboutYourDesigns=cleaned_data.get("AboutYourDesigns")
        design2=cleaned_data.get("design2")
        design3=cleaned_data.get("design3")
        return AboutMe


class ConfirmPasswordForm(forms.Form):
    old_password=forms.CharField(widget=forms.PasswordInput())
    new_password=forms.CharField(widget=forms.PasswordInput())
    def clean_message(self):
        cleaned_data=super(ConfirmPasswordForm, self).clean()
        old_password=cleaned_data.get("old_password")
        new_password=cleaned_data.get("new_password")
        return old_password


class BlogForm(forms.Form):
    title=forms.CharField()
    content=forms.CharField()
    image=forms.ImageField(required=False)

    def __init__(self, *args, **kwargs):
        super(BlogForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = False



class Comment(forms.Form):
    matter=forms.CharField()
    id=forms.IntegerField()





class DpForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(DpForm, self).__init__(*args, **kwargs)
        self.fields['profilepic'].required = False
        
    profilepic = forms.ImageField()

    def save(self,id):
        user=Designers.objects.filter(designerID=id)
        user[0].profilepic=self.cleaned_data['profilepic']
        user[0].save(update_fields=['profilepic'])








class DesignsForm(forms.Form):
    design1 = forms.ImageField()
    design1type = forms.CharField()
    design2 = forms.ImageField()
    design2type = forms.CharField()
    design3 = forms.ImageField()
    design3type = forms.CharField()

    def __init__(self, *args, **kwargs):
        super(DesignsForm, self).__init__(*args, **kwargs)
        self.fields['design1'].required = False
        self.fields['design2'].required = False
        self.fields['design3'].required=False

class AboutForm(forms.Form):
    AboutMe = forms.CharField()
    AboutYourDesigns = forms.CharField()


class AddressForm(forms.Form):
    address=forms.CharField()



class AboutEditForm(forms.Form):
    AboutMe = forms.CharField(required=False)
    AboutYourDesigns = forms.CharField(required=False)

class DesignsEditForm(forms.Form):
    design1 = forms.ImageField(required=False)
    design1type = forms.CharField(required=False)
    design2 = forms.ImageField(required=False)
    design2type = forms.CharField(required=False)
    design3 = forms.ImageField(required=False)
    design3type = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super(DesignsEditForm, self).__init__(*args, **kwargs)
        self.fields['design1'].required = False
        self.fields['design2'].required = False
        self.fields['design3'].required = False



class jobselect(forms.Form):
    jobid=forms.CharField()


class UpdatesJobform(forms.Form):
    id=forms.CharField()
    image = forms.ImageField(required=False)
    article = forms.CharField(max_length=500)


class RequestForm(forms.Form):
    object = forms.CharField()
    qty = forms.IntegerField()
    requirements = forms.CharField(required=False)

class Forgotpass(forms.Form):
    email=forms.CharField()


class fppass(forms.Form):
    otp=forms.CharField()
    password=forms.CharField()


class Loginform(forms.Form):
    userid=forms.CharField()
    password=forms.CharField()

class Designeditform(forms.Form):
    selected=forms.CharField()
    design=forms.ImageField()
    designtype=forms.CharField()

designers/templates/designers/1.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration - GharBanao</title>
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'designers/css/designerinfo.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/template.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>

</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'designers:index' %}" ><img src="{% static 'customers/img/GharBanaoLogo_nav.png' %}"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div style="position: absolute; right: 7vw;top: 25px;">


            <a href="{% url 'designers:logout' %}" class="btn my_project" >Logout<span class="sr-only">(current)</span></a></li>


        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container page" id="page">
    <center>
        <div class="row no-margin container-fluid main" style="height: 420px">
            <form method="post" action="{% url 'designers:next' status %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row" style="background: #123c88; border-radius: 6px 6px 0px 0px"><h3 class="col-xs-12" style="color: white">Our customers would like to see you</h3></div><br>

                <div class="row no-margin"> <h5>Upload a photo:</h5> </div>

                <div class="row no-margin">
                    <center>
                        <div class="row no-margin preview">
                            <img id="blah" src="{% static 'customers/img/face1.jpg'%}">

                            <input type="file" id="imgInp" name="profilepic">

                        </div>
                    </center>
                </div>
                <button type="submit"><b>Save and continue</b></button>

            </form>

        </div>
    </center>
</div>
<script>
    function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#blah').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$("#imgInp").change(function(){
    readURL(this);
});
</script>

</body>
</html>

designers/templates/designers/2.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration - GharBanao</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap.min.css' %}">

    <!-- Optional theme -->
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap-theme.min.css' %}">
    <!--<link rel="stylesheet" href="css/profile.css" >-->
    <link rel="stylesheet" href="{% static 'designers/css/designerinfo.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/template.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>


</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'designers:index' %}" ><img src="{% static 'customers/img/GharBanaoLogo_nav.png' %}"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div style="position: absolute; right: 7vw;top: 25px;">


            <a href="{% url 'designers:logout' %}" class="btn my_project" >Logout<span class="sr-only">(current)</span></a></li>


        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>


<div class="container page" id="page">
    <center>
        <div class="row no-margin container-fluid files" style="">
            <div class="row" style="background: #123c88; border-radius: 6px 6px 0px 0px"><h3 class="col-xs-12" style="color: white">Upload three of your most appreciated designs</h3></div><br>
            <form method="post" action="{% url 'designers:next' status %}" enctype="multipart/form-data" >
                {% csrf_token %}
                <div class="col-sm-4">
                    <div class="row no-margin preview">
                        <img id="blah1" src="{% static 'customers/img/face1.jpg'%}">
                        <input type="file" id="imgInp1" name="design1">
                    </div>

                    <br>
                    <select name="design1type">
                        <option>
                            Traditional
                        </option>
                        <option>
                            Modern
                        </option>
                        <option>
                            Minimalistic
                        </option>
                        <option>
                            Contemporary
                        </option>
                        <option>
                            Industrial
                        </option>
                        <option>
                            MidCenturyModern
                        </option>
                        <option>
                            Scandinian
                        </option>
                        <option>
                            Bohemian
                        </option>
                        <option>
                            Retro
                        </option>
                    </select>
                </div>


                <div class="col-sm-4">


                    <div class="row no-margin preview">
                        <img id="blah2" src="{% static 'customers/img/face1.jpg'%}">
                        <input type="file"  id="imgInp2" name="design2">

                    </div>
                    <br>
                    <select name="design2type">
                        <option>
                            Traditional
                        </option>
                        <option>
                            Modern
                        </option>
                        <option>
                            Minimalistic
                        </option>
                        <option>
                            Contemporary
                        </option>
                        <option>
                            Industrial
                        </option>
                        <option>
                            MidCenturyModern
                        </option>
                        <option>
                            Scandinian
                        </option>
                        <option>
                            Bohemian
                        </option>
                        <option>
                            Retro
                        </option>
                    </select>

                </div>

                <div class="col-sm-4">
                    <div class="row no-margin preview">
                        <img id="blah3" src="{% static 'customers/img/face1.jpg'%}">
                        <input type="file" id="imgInp3" name="design3">

                    </div>
                    <br>
                    <select name="design3type">
                        <option>
                            Traditional
                        </option>
                        <option>
                            Modern
                        </option>
                        <option>
                            Minimalistic
                        </option>
                        <option>
                            Contemporary
                        </option>
                        <option>
                            Industrial
                        </option>
                        <option>
                            MidCenturyModern
                        </option>
                        <option>
                            Scandinian
                        </option>
                        <option>
                            Bohemian
                        </option>
                        <option>
                            Retro
                        </option>
                    </select>
                </div>


                <button type="submit">Next</button>
            </form>


        </div>
    </center>
</div>
<script>
    function readURL1(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#blah1').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$("#imgInp1").change(function(){
    readURL1(this);
});
</script>
<script>
    function readURL2(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#blah2').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$("#imgInp2").change(function(){
    readURL2(this);
});
</script>
<script>
    function readURL3(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#blah3').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$("#imgInp3").change(function(){
    readURL3(this);
});
</script>

</body>
</html>

designers/templates/designers/aboutform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
<form method="post" action="{% url 'designers:edit_about'  %}" >
    {% csrf_token %}
    AboutMe: <input type="text" name="AboutMe">
    <br>
    AboutYourDesigns:<input type="text" name="AboutYourDesigns">
    <br>
    <button type="submit">Next</button>

</form>
</body>
</html>

designers/templates/designers/addressupdate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Adddress</title>
</head>
<body>
 <form method="post" action="{% url 'designers:edit_address' %}" enctype="multipart/form-data">
        {% csrf_token %}
        profilepic: <input type="text" name="address">
        <br>
        <button type="submit">Change</button>

    </form>
  <a href="{% url 'designers:login'  %}">Skip</a>
</body>
</html>

designers/templates/designers/dpupdate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile pic</title>

</head>
<body>
    <form method="post" action="{% url 'designers:edit_dp' %}" enctype="multipart/form-data">
        {% csrf_token %}
        profilepic: <input type="file" name="profilepic">
        <br>
        <button type="submit">Change</button>

    </form>
  <a href="{% url 'designers:login'  %}">Skip</a>
</body>
</html>

designers/templates/designers/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Login </title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'designers/css/designerinfo.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/template.css' %}">

</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                <center>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </center>
            </button>

            <a class="navbar-brand" href="{% url 'designers:index' %}"><img src="{% static 'customers/img/GharBanaoLogo_nav.png' %}"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav navbar-right">
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container page" id="page">
    <center>
        <div align="left" class="row no-margin container-fluid main">
            <form name = "form" action = "{% url 'designers:registeration' %}" method = "POST" style="background-color:rgba(255,255,255,0.7);border-radius:20px"  id="opening" >{% csrf_token %}

                <div class="row" style="background: #123c88; border-radius: 6px 6px 0px 0px"><h2 class="col-xs-12" style="color: white"> Designer Login</h2></div>

                <div class="row no-margin"><h5> Designer ID:</h5> </div>

                <input class="text-input" type = "text" placeholder = "DesignerID" name = "designerID">

                <div class="row no-margin"><h5> Password:</h5></div>

                <input class="text-input" type="password" placeholder="Password" name="password" >

                <p>{{errors}}</p>

                <button type="submit" value="Login">
                    LOGIN
                </button>
                <a href="{% url 'designers:fp' %}">Forgot Password</a>
                <br>

                <center style="margin-top: 10px">
                    Not signed up with GharBanao yet?
                    <br>
                    <a href="{% url 'designers:register' %}" id="register"> Click here </a> to sign up.
                </center>

            </form>
        </div>
    </center>
</div>
</body>
</body>
</html>