DesignerWebsite/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.core.mail import send_mail
from django.shortcuts import render
from designers.models import Designers,Rawpass
from django.core.files.storage import FileSystemStorage
from designers.forms import SendMail
from django.core.mail import send_mail
from django.conf import settings
from gbstore.models import *
from rest_framework import routers
from apis import views
from rest_framework.urlpatterns import format_suffix_patterns
from datetime import datetime,date
from gbstore.forms import ProductAdd,PlywoodAddForm,LaminatesAddForm,AdhesiveAdd
import random
import string
from django.contrib.auth.hashers import make_password
from merchant.forms import MerchantAddForm,SGForm,merchantSearch
from merchant.models import *
from designers.models import Designers



def Mail(request):
    email=""
    if request.method == "POST":
        MyRegisterForm = SendMail(request.POST)
        if MyRegisterForm.is_valid():
            Send_To=MyRegisterForm.cleaned_data['Send_To']
            dbuser = Designers.objects.filter(email=Send_To)
            if dbuser:
                user=dbuser[0]
                randpass=''.join(random.choice(string.ascii_uppercase+string.digits) for _ in range(8))
                dbuser[0].password=make_password(randpass)
                dbuser[0].designerID='GBIDX0{0}'.format(Designers.objects.count())
                rawpass=Rawpass(rawpass=randpass,designer=dbuser[0])
                rawpass.save()
                dbuser[0].save()
                contact_message =  'Your DesignerId is {0} and password is  {1} '.format(user.designerID,randpass)
                from_email = settings.EMAIL_HOST_USER
                to_email = []
                to_email.append(Send_To)
                send_mail('Registration Succesfull', contact_message, from_email, to_email, fail_silently=False)



        else:
            MyRegisterForm = SendMail(request.GET)

    return render(request, 'designers/SendMails.html',{})

def product_add(request):
    errors=""

    if request.method=='POST':
        myform=ProductAdd(request.POST,request.FILES)

        if myform.is_valid():
            p=Products()
            count=Products.objects.count()+1
            p.gbcode='GBPRO0{0}'.format(count)
            if myform.cleaned_data['comp_code']:
                p.comp_code = myform.cleaned_data['comp_code']
            else:
                p.comp_code=p.gbcode

            p.name=myform.cleaned_data['name']
            p.company=myform.cleaned_data['company']
            p.address=myform.cleaned_data['address']
            if myform.cleaned_data['description']:
              p.description=myform.cleaned_data['description']
            if myform.cleaned_data['colour']:
                p.colour=myform.cleaned_data['colour']
            if myform.cleaned_data['length']:
                p.length=myform.cleaned_data['length']
            if myform.cleaned_data['height']:
                p.height=myform.cleaned_data['height']
            if myform.cleaned_data['radius']:
                p.radius=myform.cleaned_data['radius']
            p.image1=myform.cleaned_data['image1']
            if myform.cleaned_data['image2']:
                p.image2=myform.cleaned_data['image2']
            p.original_price=myform.cleaned_data['original_price']
            p.cost_price=myform.cleaned_data['cost_price']
            p.selling_price=myform.cleaned_data['selling_price']
            p.profit=((p.selling_price-p.cost_price)/p.cost_price)*100
            if myform.cleaned_data['star']:
                p.star=True
            else:
                p.star=False
            p.date=datetime.now()
            p.save()
            context = {'errors': errors}
            return render(request, 'gbstore/product_add.html', context=context)


        else:
            print(myform.errors)
            errors="Not Inserted"
    context = {'errors': errors}
    return render(request,'gbstore/product_add.html',context=context)

def product_search(request):


    products=list(Products.objects.filter(star=True).order_by('-date')[:10])
    nonstar=Products.objects.filter(star=False).order_by('date')[:20]
    for x in nonstar:
        products.append(x)
    random.shuffle(products)
    new=Products.objects.filter(new=True).order_by('date')[:10]
    if request.method=='POST':
        products=[]
        products=list(Products.objects.filter(name__contains=request.POST['search']).order_by('date'))
        products.extend(list(Products.objects.filter(company__contains=request.POST['search']).order_by('date')))
        products.extend(list(Products.objects.filter(description__contains=request.POST['search']).order_by('date')))
        new=[]
    context={
        'products':products,
        'new':new,
    }
    return render(request, 'gbstore/product_search.html', context=context)

def product_update(request):
    errors = ""
    context = {'errors': errors}
    return render(request, 'gbstore/product_add.html', context=context)


def plywood_add(request):
    if request.method=='POST':

        myform=PlywoodAddForm(request.POST,request.FILES)
        print(request.POST.getlist('vendor'))
        if myform.is_valid():
            ply=Plywood()
            ply.brand = myform.cleaned_data['brand']
            ply.dimention = myform.cleaned_data['dimention']
            ply.Thickness = myform.cleaned_data['Thickness']
            ply.series = myform.cleaned_data['series']
            if myform.cleaned_data['img1']:
                ply.img1 = myform.cleaned_data['img1']
            if myform.cleaned_data['img2']:
                ply.img2 = myform.cleaned_data['img2']
            if myform.cleaned_data['compcode']:
                ply.compcode = myform.cleaned_data['compcode']
            if myform.cleaned_data['description']:
                ply.description = myform.cleaned_data['description']
            ply.original_price = myform.cleaned_data['original_price']
            ply.cost_price = myform.cleaned_data['cost_price']
            ply.selling_price = myform.cleaned_data['selling_price']
            ply.date=datetime.now()
            code=Plywood.objects.count()+1
            ply.gbcode='GBPLY0{0}'.format(code)
            gbcode=ply.gbcode
            ply.save()
            for x in request.POST.getlist('vendor'):

                if Merchants.objects.filter(merchantID=x):
                    merch=Mercentdise()
                    merch.type="Plywood"
                    merch.merchant=Merchants.objects.get(merchantID=x)
                    merch.gbcode=gbcode
                    merch.save()
            br=Brand.objects.filter(name=ply.brand,typ='Plywood')
            if not br:
                br1=Brand()
                br1.name=ply.brand
                br1.typ='Plywood'
                br1.save()
            dim = Dimention.objects.filter(name=ply.dimention, typ='Plywood')
            if not dim:
                dim1 = Dimention()
                dim1.name = ply.dimention
                dim1.typ = 'Plywood'
                dim1.save()
            thik=Thickness.objects.filter(name=ply.Thickness,typ='Plywood')
            if not thik:
                thik1 = Thickness()
                thik1.name = ply.Thickness
                thik1.typ = 'Plywood'
                thik1.save()
    vendor = list(Merchants.objects.all())

    content={

        'merchants':vendor
    }
    return render(request,'gbstore/plywood_add.html',content)


def laminates_add(request):
    if request.method=='POST':
        myform=LaminatesAddForm(request.POST,request.FILES)
        if myform.is_valid():
            ply=Laminates()
            ply.brand = myform.cleaned_data['brand']
            ply.dimention = myform.cleaned_data['dimention']
            ply.Thickness = myform.cleaned_data['Thickness']
            ply.series = myform.cleaned_data['series']
            if myform.cleaned_data['img1']:
                ply.img1 = myform.cleaned_data['img1']
            if myform.cleaned_data['img2']:
                ply.img2 = myform.cleaned_data['img2']
            if myform.cleaned_data['compcode']:
                ply.compcode = myform.cleaned_data['compcode']
            if myform.cleaned_data['description']:
                ply.description = myform.cleaned_data['description']
            ply.original_price = myform.cleaned_data['original_price']
            ply.cost_price = myform.cleaned_data['cost_price']
            ply.selling_price = myform.cleaned_data['selling_price']
            ply.date=datetime.now()
            code=Laminates.objects.count()+1
            ply.gbcode='GBLAM0{0}'.format(code)
            ply.dim = myform.cleaned_data['dim']
            ply.finish = myform.cleaned_data['finish']
            ply.save()
            for x in request.POST.getlist('vendor'):

                if Merchants.objects.filter(merchantID=x):
                    merch=Mercentdise()
                    merch.type="Laminates"
                    merch.merchant=Merchants.objects.get(merchantID=x)
                    merch.gbcode=ply.gbcode
                    merch.save()
            br = Brand.objects.filter(name=ply.brand, typ='Laminates')
            if not br:
                br1 = Brand()
                br1.name = ply.brand
                br1.typ = 'Laminates'
                br1.save()
            dim = Dimention.objects.filter(name=ply.dimention, typ='Laminates')
            if not dim:
                dim1 = Dimention()
                dim1.name = ply.dimention
                dim1.typ = 'Laminates'
                dim1.save()
            thik = Thickness.objects.filter(name=ply.Thickness, typ='Laminates')
            if not thik:
                thik1 = Thickness()
                thik1.name = ply.Thickness
                thik1.typ = 'Laminates'
                thik1.save()

apis/urls.py
from django.conf.urls import url
from functools import wraps
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name='apis'


def csrf_exempt(view_func):
    def wrapped_view(request,*args,**kwargs):
        return view_func(request,*args,**kwargs)
    wrapped_view.csrf_exempt=True
    return wraps(view_func,)(wrapped_view)


urlpatterns = format_suffix_patterns( [
    url(r'^hu/$', views.IndexViewSet.as_view()),
    url(r'^humi/$', csrf_exempt(views.Login.as_view())),
    url(r'^humis/$', csrf_exempt(views.SearchBlogs.as_view())),
    url(r'^ru/$', csrf_exempt(views.CreateBlog.as_view())),
    url(r'^rumi/$', csrf_exempt(views.DesignerBlogs.as_view())),
    url(r'^rumis/$', csrf_exempt(views.LikeView.as_view())),
    url(r'^sayonara/$', csrf_exempt(views.Logout.as_view())),



    #url(r'^sl/$', csrf_exempt(views.StoreLogin.as_view())),
])

customers/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name='customers'


urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^designs$', views.search,name='search'),
    url(r'^blogs$',views.blogs,name='blogs'),
    url(r'^job_description$',views.job,name='job'),
    url(r'^job_personal$',views.job2,name='job2'),
    url(r'^designer_select$',views.designer,name='designer'),
    url(r'^designer_selected$',views.designer_selected,name='designer_selected'),
    url(r'^otp', views.otp, name='otp'),
    url(r'^make_payment$', views.make_payment, name='make_payment'),
    url(r'^successfull$',views.successfull, name='successfull'),
    url(r'^login$',views.login, name='login'),
    url(r'^logout$',views.logout, name='logout'),
    url(r'^profile_details',views.profile_handler,name='profile_handler'),
    url(r'^update_post',views.update,name="update"),
    url(r'^howitworks',views.howitworks,name='howitworks'),
    url(r'^ourdesign$',views.ourdesign,name='ourdesign'),
    #url(r'^testing$',views.testblogs,name='testblogs'),
    url(r'^blogview/$', views.specific_blog, name='specific_blog'),
    url(r'^resend$', views.resend, name='resend'),
    url(r'^tnc$', views.tnc, name='tnc'),
    url(r'^policy$', views.policy, name='policy'),
    url(r'^about$', views.about, name='about'),
    url(r'^career$', views.career, name='career'),
    url(r'^test$', views.test, name='test'),










]

designers/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views

app_name='designers'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'register/$', views.DesignerCreate.as_view(), name='register'),
    url(r'login/$', views.login, name='login'),
    url(r'dashboard/$', views.registeration, name='registeration'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'registerconf/$', views.regcon, name='regcon'),
    url(r'our_designers', views.designersview, name='ourDes'),
    url(r'change_password/$', views.change_password, name='password_change'),
    url(r'wrong_password/$', views.wrongPassword, name='wrongPassword'),
    url(r'create_blog/$', views.blog, name='blog'),
    url(r'view_blogs/$',views.blog_search,name='blogsearch'),
    url(r'^(?P<status>[0-9]+)/$',views.next,name='next'),
    url(r'^dp_change/$',views.edit_dp,name='edit_dp'),
    url(r'^address_change/$',views.edit_address,name='edit_address'),
    url(r'^about_change/$',views.edit_about,name='edit_about'),
    url(r'^jobs/$',views.myjobs,name='myjobs'),
    url(r'^editjob/$',views.editjob,name='editjob'),
    url(r'^update/$',views.update,name='update'),
    url(r'^requestitem',views.requestitem,name='requestitem'),
    #url(r'^design/$', views.designs, name='design'),
    url(r'^login1/$', views.login1, name='login1'),
    url(r'^logout1/$', views.logout1, name='logout1'),
    url(r'^edit_des/$',views.edit_designs,name='edit_designs'),
    url(r'^forgotpass/$', views.forgotpass, name='fp'),
    url(r'^forgotpass/update/$', views.passmatch, name='fpu'),
    url(r'^resendotp/$', views.resendotp, name='reotp'),
    url(r'^test/$', views.test, name='test'),



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/models.py
from django.db import models
from designers.models import *

# Create your models here.
class Job(models.Model):
    roomtype = models.CharField(max_length=15)
    lifespan = models.CharField(max_length=20)
    execution = models.BooleanField(default=False)
    area = models.FloatField()
    estimatedbudget = models.IntegerField()
    requirements = models.TextField(max_length=200,blank=True,null=True)
    email=models.EmailField(max_length=100)
    designer=models.ForeignKey(Designers,on_delete=models.CASCADE)
    job_started=models.BooleanField(default=False)
    password=models.CharField(max_length=50)
    name=models.CharField(max_length=100,null=True)
    contact=models.CharField(max_length=14,null=True)
    date=models.DateTimeField(default=datetime.now())

    def __str__(self):
       return self.email



class Complains(models.Model):
    to=models.ForeignKey(Designers, on_delete=models.CASCADE,blank=True,null=True)
    by=models.ForeignKey(Job,on_delete=models.CASCADE)
    complain=models.CharField(max_length=2000)
    date=models.DateField(default=datetime.now())


class Updates(models.Model):
    job=models.ForeignKey(Job,on_delete=models.CASCADE)
    author=models.CharField(max_length=100)
    date = models.DateTimeField(default=datetime.now())
    image=models.ImageField(null=True,blank=True)
    article=models.TextField(max_length=500)
    designer=models.BooleanField(default=False)

    def __str__(self):
       return self.article

customers/forms.py
from django import forms

class BlogsForm(forms.Form):
    searchfield=forms.CharField()

class JobInitial(forms.Form):
    roomtype=forms.CharField()
    lifespan=forms.CharField()
    execution=forms.CharField()
    area=forms.FloatField()
    estimatedbudget=forms.IntegerField()
    #requirements=forms.CharField(required=False)
    false_ceiling=forms.CharField(required=False)
    flooring=forms.CharField(required=False)
    wall_paper=forms.CharField(required=False)
    wall_painting=forms.CharField(required=False)
    luxury_goods=forms.CharField(required=False)




class JobSecondStage(forms.Form):
    name=forms.CharField()
    email=forms.EmailField()
    freetime=forms.DateTimeInput()
    contact=forms.CharField()

class Otp(forms.Form):
    otp=forms.CharField()


class LoginForm(forms.Form):
    email=forms.EmailField()
    password=forms.CharField()



class ComplainForm(forms.Form):
    complain=forms.CharField()
    time=forms.DateInput()


class DesignSearch(forms.Form):
    search=forms.CharField()


class Updatesform(forms.Form):
    image = forms.ImageField(required=False)
    article = forms.CharField(max_length=500)


class SelectBlog(forms.Form):
    url=forms.IntegerField()

customers/templates/customers/ajax_search.html
{% if designers.count > 0 %}


{% for  designer in designers %}
  <li>{{designer.name}}</li>
{% endfor %}

{% endif %}

customers/templates/customers/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <form method="post" action="{% url 'customers:login' %}">
        {% csrf_token %}
        <input name="email" type="text">
        <input name="password" type="password">
        <button type="submit">Login</button>
    </form>
</body>
</html>

customers/templates/customers/designs.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
    <link rel="shortcut icon" type="image/png" href="{% static 'customers/img/favicon.png' %}"/>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Design Gallery - GharBanao</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="{% static 'customers/css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static 'customers/css/template.css' %}" >
    <link rel="stylesheet" href="{% static 'customers/css/designs.css' %}" >

</head>


<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">

                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </button>

            <a class="navbar-brand" href="{% url 'customers:index' %}"><img src="{% static 'customers/img/GharBanaoLogo_nav.png' %}"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar">


            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'customers:howitworks' %}">How it works<span class="sr-only">(current)</span></a></li>
                <!--<li><a href="{% url 'customers:blogs' %}">Helpdesk<span class="sr-only">(current)</span></a></li>-->
                <li><a href="{% url 'customers:ourdesign' %}">Designs<span class="sr-only">(current)</span></a></li>
                <li><a href="{% url 'customers:blogs' %}">Blog<span class="sr-only">(current)</span></a></li>
                <li><button type="button" class="btn my_project" data-toggle="collapse" data-target="#login" aria-controls="nav-collapse" >My Project</button></li>

                <div id="login" class="collapse">
                    <div class="login_window">
                        <button type="button" class="close" data-toggle="collapse" data-target="#login">&times;</button>
                        <form class="login-form" method="post" action="{% url 'customers:login' %}">
                            {% csrf_token %}
                            <br>
                            <h2>Login</h2>
                            <input type="text" placeholder="Enter ProjectID" name="email" required>
                            <input type="password" placeholder="Enter password" name="password" required>

                            <button type="submit">Login</button>
                        </form>
                        <br>
                    </div>
                </div>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<!-- End of nav -->

<div class="container-fluid page" id="page">
    <center>
    <div class="row container-fluid no-margin page-title">
        <div class="col-sm-6" align="left">
            <h1 class="border_right">Our Designs</h1>
        </div>

        <div class="col-sm-6 filter" align="right">
            <form method="get" action="{% url 'customers:ourdesign' %}">
                <select  name="search">
                    <option>
                        Traditional
                    </option>
                    <option>
                        Modern
                    </option>
                    <option>
                        Minimalistic
                    </option>
                    <option>
                        Contemporary
                    </option>
                    <option>
                        Industrial
                    </option>
                    <option>
                        MidCenturyModern
                    </option>
                    <option>
                        Scandinian
                    </option>
                    <option>
                        Bohemian
                    </option>
                    <option>
                        Retro
                    </option>
                </select>
                <button type="submit">Search </button>

            </form>
        </div>
    </div>
    </center>
    <hr>
    <center><h3>{{header}}</h3></center>
    <hr>

    <div class="row container-fluid no-margin">
        <div class="row container-fluid no-margin">
            {% for x in ourimg %}
            <div class="col-sm-4 no-padding frame">
                <div class="des" style="background: url({{x.0}}) no-repeat center">
                    <div class="col-xs-12 no-padding cover">
                        <div class="col-xs-12 details">
                            <div class="col-xs-2 no-padding">
                                <img src="{{x.1.profilepic.url}}" class="img-responsive">
                            </div>

                            <div class="col-xs-10">
                                <h3>{{x.1.name}}</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <hr>



    <!--footer-->
        <!--footer-->
    <div class="container footer">
        <div class="row"><!-- row -->

            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12 tyc"><!-- widgets column center -->
                <img class="img-responsive" src="{% static 'customers/img/logo_bw.png' %}">
            </div>

            <div class="col-lg-7 col-md-7 col-sm-7 col-xs-12">


                <div class="col-sm-4 col-xs-6 mycol list"><!-- widgets column left -->

                    <h4 class="title-widget">COMPANY</h4>
                    <ul>
                        <li><a href="{% url 'customers:about' %}">About Us</a></li>
                        <li><a href="{% url 'customers:career' %}">Career </a></li>
                        <li><a href="mailto:enquiry@gharbanao.co?Subject=Enquiry" target="_blank">Contact Us</a></li>
                        <li><a href="{% url 'designers:index' %}" target="_blank">Designers</a></li>
                        <li><a href="mailto:admin@gharbanao.co?Subject=Feedback" target="_blank"">Feedback</a></li>


                    </ul>


                </div><!-- widgets column left end -->

                <div class="col-sm-4 col-xs-6 mycol list"><!-- widgets column left -->

                    <h4 class="title-widget">LEGAL</h4>
                    <ul>
                        <li><a  href="{% url 'customers:tnc' %}">Terms and Conditions</a></li>
                        <li><a  href="{% url 'customers:policy' %}">Privacy Policy</a></li>
                    </ul>
                </div><!-- widgets column left end -->



                <div class="col-sm-4 col-xs-12 mycol list"><!-- widgets column left -->
                    <h4 class="title-widget">CONNECT</h4>
                    <div class="social-icons">
                        <a href="https://www.facebook.com/GharBanao/"><img src="{% static 'customers/img/fb.png' %}"></a>
                        <a href="https://twitter.com/GharBanao"><img src="{% static 'customers/img/tweet.png' %}"></a>
                        <a href="https://instagram.com/gharbanao"><img src="{% static 'customers/img/inst.png' %}"></a>
                        <a href="https://www.linkedin.com/company-beta/10652164/"><img src="{% static 'customers/img/in.png' %}"></a><br>
                    </div>
                </div>
            </div>
        </div>
        <center><p class="copyright"> Copyright © 2017 Tune Your Construction (P) Ltd.</p></center>
    </div>




</div>
<script src="{% static 'customers/js/jquery.min.js' %}"></script>
<script src="{% static 'customers/js/bootstrap.min.js' %}"></script>
<script>
$(document).mouseup(function(e)
{
    var container = $("#login");


    if (!container.is(e.target) && container.has(e.target).length === 0)
    {
        container.removeClass("in");
    }
});
</script>

<script>
$(document).mouseup(function(e)
{
    var container1 = $(".navbar-collapse");
    var container2 = $(".navbar-toggle");

    if (!container2.is(e.target) && container2.has(e.target).length === 0)
        {    if (!container1.is(e.target) && container1.has(e.target).length === 0)
            {
                container1.removeClass("in");
            }
        }
});
</script>

</body>
</html>

customers/templates/customers/wait.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
    <link rel="shortcut icon" type="image/png" href="{% static 'customers/img/favicon.png' %}"/>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GharBanao - Interior design hub</title>
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap-theme.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'customers/css/info_page.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/template.css' %}">
</head>

<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                <center>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </center>
            </button>

            <a class="navbar-brand" href="{% url 'customers:index' %}"><img src="{% static 'customers/img/GharBanaoLogo_nav.png' %}"></a>
        </div>

    </div><!-- /.container-fluid -->
</nav>

<!-- End of nav -->

<div class="container page" id="page">


    <!-- Page Starts-->
    <center>
        <div class="info-win">
            <h3 style="color: #123c88">Waiting for your designer</h3>
            <hr>
            <h5 style="color: #333">Please wait till the designer accepts your project. You can login to your My Project page once the designer accepts your project.git a</h5>
        </div>
    <center>
            <!-- Page Ends-->




            <!--footer-->
                <!--footer-->
    <div class="container footer">
        <div class="row"><!-- row -->

            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12 tyc"><!-- widgets column center -->
                <img class="img-responsive" src="{% static 'customers/img/logo_bw.png' %}">
            </div>

            <div class="col-lg-7 col-md-7 col-sm-7 col-xs-12">


                <div class="col-sm-4 col-xs-6 mycol list"><!-- widgets column left -->

                    <h4 class="title-widget">COMPANY</h4>
                    <ul>
                        <li><a href="{% url 'customers:about' %}">About Us</a></li>
                        <li><a href="{% url 'customers:career' %}">Career </a></li>
                        <li><a href="mailto:enquiry@gharbanao.co?Subject=Enquiry" target="_blank">Contact Us</a></li>
                        <li><a href="{% url 'designers:index' %}" target="_blank">Designers</a></li>
                        <li><a href="mailto:admin@gharbanao.co?Subject=Feedback" target="_blank"">Feedback</a></li>


                    </ul>


                </div><!-- widgets column left end -->

                <div class="col-sm-4 col-xs-6 mycol list"><!-- widgets column left -->

                    <h4 class="title-widget">LEGAL</h4>
                    <ul>
                        <li><a  href="{% url 'customers:tnc' %}">Terms and Conditions</a></li>
                        <li><a  href="{% url 'customers:policy' %}">Privacy Policy</a></li>
                    </ul>
                </div><!-- widgets column left end -->



                <div class="col-sm-4 col-xs-12 mycol list"><!-- widgets column left -->
                    <h4 class="title-widget">CONNECT</h4>
                    <div class="social-icons">
                        <a href="https://www.facebook.com/GharBanao/"><img src="{% static 'customers/img/fb.png' %}"></a>
                        <a href="https://twitter.com/GharBanao"><img src="{% static 'customers/img/tweet.png' %}"></a>
                        <a href="https://instagram.com/gharbanao"><img src="{% static 'customers/img/inst.png' %}"></a>
                        <a href="https://www.linkedin.com/company-beta/10652164/"><img src="{% static 'customers/img/in.png' %}"></a><br>
                    </div>
                </div>
            </div>
        </div>
        <center><p class="copyright"> Copyright © 2017 Tune Your Construction (P) Ltd.</p></center>
    </div>




</div>
<script src="{% static 'customers/js/jquery.min.js' %}"></script>
<script src="{% static 'customers/js/bootstrap.min.js' %}"></script>

</body>
</html>