DesignerWebsite/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.core.mail import send_mail
from django.shortcuts import render
from designers.models import Designers,Rawpass
from django.core.files.storage import FileSystemStorage
from designers.forms import SendMail
from django.core.mail import send_mail
from django.conf import settings
from gbstore.models import *
from rest_framework import routers
from apis import views
from rest_framework.urlpatterns import format_suffix_patterns
from datetime import datetime,date
from gbstore.forms import ProductAdd,PlywoodAddForm,LaminatesAddForm,AdhesiveAdd
import random
import string
from django.contrib.auth.hashers import make_password
from merchant.forms import MerchantAddForm,SGForm,merchantSearch
from merchant.models import *
from designers.models import Designers



def Mail(request):
    email=""
    if request.method == "POST":
        MyRegisterForm = SendMail(request.POST)
        if MyRegisterForm.is_valid():
            Send_To=MyRegisterForm.cleaned_data['Send_To']
            dbuser = Designers.objects.filter(email=Send_To)
            if dbuser:
                user=dbuser[0]
                randpass=''.join(random.choice(string.ascii_uppercase+string.digits) for _ in range(8))
                dbuser[0].password=make_password(randpass)
                dbuser[0].designerID='GBIDX0{0}'.format(Designers.objects.count())
                rawpass=Rawpass(rawpass=randpass,designer=dbuser[0])
                rawpass.save()
                dbuser[0].save()
                contact_message =  'Your DesignerId is {0} and password is  {1} '.format(user.designerID,randpass)
                from_email = settings.EMAIL_HOST_USER
                to_email = []
                to_email.append(Send_To)
                send_mail('Registration Succesfull', contact_message, from_email, to_email, fail_silently=False)



        else:
            MyRegisterForm = SendMail(request.GET)

    return render(request, 'designers/SendMails.html',{})

def product_add(request):
    errors=""

    if request.method=='POST':
        myform=ProductAdd(request.POST,request.FILES)

        if myform.is_valid():
            p=Products()
            count=Products.objects.count()+1
            p.gbcode='GBPRO0{0}'.format(count)
            if myform.cleaned_data['comp_code']:
                p.comp_code = myform.cleaned_data['comp_code']
            else:
                p.comp_code=p.gbcode

            p.name=myform.cleaned_data['name']
            p.company=myform.cleaned_data['company']
            p.address=myform.cleaned_data['address']
            if myform.cleaned_data['description']:
              p.description=myform.cleaned_data['description']
            if myform.cleaned_data['colour']:
                p.colour=myform.cleaned_data['colour']
            if myform.cleaned_data['length']:
                p.length=myform.cleaned_data['length']
            if myform.cleaned_data['height']:
                p.height=myform.cleaned_data['height']
            if myform.cleaned_data['radius']:
                p.radius=myform.cleaned_data['radius']
            p.image1=myform.cleaned_data['image1']
            if myform.cleaned_data['image2']:
                p.image2=myform.cleaned_data['image2']
            p.original_price=myform.cleaned_data['original_price']
            p.cost_price=myform.cleaned_data['cost_price']
            p.selling_price=myform.cleaned_data['selling_price']
            p.profit=((p.selling_price-p.cost_price)/p.cost_price)*100
            if myform.cleaned_data['star']:
                p.star=True
            else:
                p.star=False
            p.date=datetime.now()
            p.save()
            context = {'errors': errors}
            return render(request, 'gbstore/product_add.html', context=context)


        else:
            print(myform.errors)
            errors="Not Inserted"
    context = {'errors': errors}
    return render(request,'gbstore/product_add.html',context=context)

def product_search(request):


    products=list(Products.objects.filter(star=True).order_by('-date')[:10])
    nonstar=Products.objects.filter(star=False).order_by('date')[:20]
    for x in nonstar:
        products.append(x)
    random.shuffle(products)
    new=Products.objects.filter(new=True).order_by('date')[:10]
    if request.method=='POST':
        products=[]
        products=list(Products.objects.filter(name__contains=request.POST['search']).order_by('date'))
        products.extend(list(Products.objects.filter(company__contains=request.POST['search']).order_by('date')))
        products.extend(list(Products.objects.filter(description__contains=request.POST['search']).order_by('date')))
        new=[]
    context={
        'products':products,
        'new':new,
    }
    return render(request, 'gbstore/product_search.html', context=context)

def product_update(request):
    errors = ""
    context = {'errors': errors}
    return render(request, 'gbstore/product_add.html', context=context)


def plywood_add(request):
    if request.method=='POST':

        myform=PlywoodAddForm(request.POST,request.FILES)
        print(request.POST.getlist('vendor'))
        if myform.is_valid():
            ply=Plywood()
            ply.brand = myform.cleaned_data['brand']
            ply.dimention = myform.cleaned_data['dimention']
            ply.Thickness = myform.cleaned_data['Thickness']
            ply.series = myform.cleaned_data['series']
            if myform.cleaned_data['img1']:
                ply.img1 = myform.cleaned_data['img1']
            if myform.cleaned_data['img2']:
                ply.img2 = myform.cleaned_data['img2']
            if myform.cleaned_data['compcode']:
                ply.compcode = myform.cleaned_data['compcode']
            if myform.cleaned_data['description']:
                ply.description = myform.cleaned_data['description']
            ply.original_price = myform.cleaned_data['original_price']
            ply.cost_price = myform.cleaned_data['cost_price']
            ply.selling_price = myform.cleaned_data['selling_price']
            ply.date=datetime.now()
            code=Plywood.objects.count()+1
            ply.gbcode='GBPLY0{0}'.format(code)
            gbcode=ply.gbcode
            ply.save()
            for x in request.POST.getlist('vendor'):

                if Merchants.objects.filter(merchantID=x):
                    merch=Mercentdise()
                    merch.type="Plywood"
                    merch.merchant=Merchants.objects.get(merchantID=x)
                    merch.gbcode=gbcode
                    merch.save()
            br=Brand.objects.filter(name=ply.brand,typ='Plywood')
            if not br:
                br1=Brand()
                br1.name=ply.brand
                br1.typ='Plywood'
                br1.save()
            dim = Dimention.objects.filter(name=ply.dimention, typ='Plywood')
            if not dim:
                dim1 = Dimention()
                dim1.name = ply.dimention
                dim1.typ = 'Plywood'
                dim1.save()
            thik=Thickness.objects.filter(name=ply.Thickness,typ='Plywood')
            if not thik:
                thik1 = Thickness()
                thik1.name = ply.Thickness
                thik1.typ = 'Plywood'
                thik1.save()
    vendor = list(Merchants.objects.all())

    content={

        'merchants':vendor
    }
    return render(request,'gbstore/plywood_add.html',content)


def laminates_add(request):
    if request.method=='POST':
        myform=LaminatesAddForm(request.POST,request.FILES)
        if myform.is_valid():
            ply=Laminates()
            ply.brand = myform.cleaned_data['brand']
            ply.dimention = myform.cleaned_data['dimention']
            ply.Thickness = myform.cleaned_data['Thickness']
            ply.series = myform.cleaned_data['series']
            if myform.cleaned_data['img1']:
                ply.img1 = myform.cleaned_data['img1']
            if myform.cleaned_data['img2']:
                ply.img2 = myform.cleaned_data['img2']
            if myform.cleaned_data['compcode']:
                ply.compcode = myform.cleaned_data['compcode']
            if myform.cleaned_data['description']:
                ply.description = myform.cleaned_data['description']
            ply.original_price = myform.cleaned_data['original_price']
            ply.cost_price = myform.cleaned_data['cost_price']
            ply.selling_price = myform.cleaned_data['selling_price']
            ply.date=datetime.now()
            code=Laminates.objects.count()+1
            ply.gbcode='GBLAM0{0}'.format(code)
            ply.dim = myform.cleaned_data['dim']
            ply.finish = myform.cleaned_data['finish']
            ply.save()
            for x in request.POST.getlist('vendor'):

                if Merchants.objects.filter(merchantID=x):
                    merch=Mercentdise()
                    merch.type="Laminates"
                    merch.merchant=Merchants.objects.get(merchantID=x)
                    merch.gbcode=ply.gbcode
                    merch.save()
            br = Brand.objects.filter(name=ply.brand, typ='Laminates')
            if not br:
                br1 = Brand()
                br1.name = ply.brand
                br1.typ = 'Laminates'
                br1.save()
            dim = Dimention.objects.filter(name=ply.dimention, typ='Laminates')
            if not dim:
                dim1 = Dimention()
                dim1.name = ply.dimention
                dim1.typ = 'Laminates'
                dim1.save()
            thik = Thickness.objects.filter(name=ply.Thickness, typ='Laminates')
            if not thik:
                thik1 = Thickness()
                thik1.name = ply.Thickness
                thik1.typ = 'Laminates'
                thik1.save()

apis/urls.py
from django.conf.urls import url
from functools import wraps
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name='apis'


def csrf_exempt(view_func):
    def wrapped_view(request,*args,**kwargs):
        return view_func(request,*args,**kwargs)
    wrapped_view.csrf_exempt=True
    return wraps(view_func,)(wrapped_view)


urlpatterns = format_suffix_patterns( [
    url(r'^hu/$', views.IndexViewSet.as_view()),
    url(r'^humi/$', csrf_exempt(views.Login.as_view())),
    url(r'^humis/$', csrf_exempt(views.SearchBlogs.as_view())),
    url(r'^ru/$', csrf_exempt(views.CreateBlog.as_view())),
    url(r'^rumi/$', csrf_exempt(views.DesignerBlogs.as_view())),
    url(r'^rumis/$', csrf_exempt(views.LikeView.as_view())),
    url(r'^sayonara/$', csrf_exempt(views.Logout.as_view())),



    #url(r'^sl/$', csrf_exempt(views.StoreLogin.as_view())),
])

designers/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views

app_name='designers'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'register/$', views.DesignerCreate.as_view(), name='register'),
    url(r'login/$', views.login, name='login'),
    url(r'dashboard/$', views.registeration, name='registeration'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'registerconf/$', views.regcon, name='regcon'),
    url(r'our_designers', views.designersview, name='ourDes'),
    url(r'change_password/$', views.change_password, name='password_change'),
    url(r'wrong_password/$', views.wrongPassword, name='wrongPassword'),
    url(r'create_blog/$', views.blog, name='blog'),
    url(r'view_blogs/$',views.blog_search,name='blogsearch'),
    url(r'^(?P<status>[0-9]+)/$',views.next,name='next'),
    url(r'^dp_change/$',views.edit_dp,name='edit_dp'),
    url(r'^address_change/$',views.edit_address,name='edit_address'),
    url(r'^about_change/$',views.edit_about,name='edit_about'),
    url(r'^jobs/$',views.myjobs,name='myjobs'),
    url(r'^editjob/$',views.editjob,name='editjob'),
    url(r'^update/$',views.update,name='update'),
    url(r'^requestitem',views.requestitem,name='requestitem'),
    #url(r'^design/$', views.designs, name='design'),
    url(r'^login1/$', views.login1, name='login1'),
    url(r'^logout1/$', views.logout1, name='logout1'),
    url(r'^edit_des/$',views.edit_designs,name='edit_designs'),
    url(r'^forgotpass/$', views.forgotpass, name='fp'),
    url(r'^forgotpass/update/$', views.passmatch, name='fpu'),
    url(r'^resendotp/$', views.resendotp, name='reotp'),
    url(r'^test/$', views.test, name='test'),



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gbstore/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views

app_name='gbstore'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ref$',views.ref,name='ref'),
    url(r'^filter$',views.filter,name='fil'),
    url(r'^login$',views.login,name='login'),
    url(r'^logout$',views.logout,name='logout'),
    url(r'quantity$',views.quantity,name='quantity'),
    url(r'^mycart$',views.mycart,name='mycart'),
    url(r'^deletecart',views.deletecart,name='deletecart'),
    url(r'^place_order',views.placeorder,name='place_order'),
    url(r'^delete_product$',views.delete_product,name='delete_product'),
    url(r'^view_product', views.view_product, name='view_product'),
	url(r'^test$',views.test,name='test'),
    url(r'^plyorder$',views.plyorder,name='plyorder'),
    url(r'^adhesiveorder$',views.adhesiveorder,name='adhesiveorder'),
    url(r'^paintorder$',views.paintorder,name='paintorder'),
    url(r'^lamorder$',views.lamorder,name='lamorder')

]

gbstore/forms.py
from django import forms
from datetime import datetime,date

class LoginForm(forms.Form):
    designerID=forms.CharField()
    password=forms.CharField()


class ProductAdd(forms.Form):
    comp_code = forms.CharField(required=False)
    name = forms.CharField()
    company = forms.CharField()
    address = forms.CharField()
    description = forms.CharField(required=False)
    colour = forms.CharField(required=False)
    length = forms.IntegerField(required=False)
    height = forms.IntegerField(required=False)
    breadth = forms.IntegerField(required=False)
    radius = forms.IntegerField(required=False)
    image1 = forms.ImageField(required=False)
    image2 = forms.ImageField(required=False)
    original_price = forms.FloatField()
    cost_price = forms.FloatField()
    selling_price = forms.FloatField()
    star = forms.BooleanField(required=False)


class SearchForm(forms.Form):
    search=forms.CharField(required=False)


class PlywoodAddForm(forms.Form):
    brand = forms.CharField()
    dimention = forms.CharField()
    Thickness = forms.IntegerField()
    series = forms.CharField()
    img1 = forms.ImageField(required=False)
    img2 = forms.ImageField(required=False)
    compcode = forms.CharField(required=False)
    description = forms.CharField(required=False)
    original_price = forms.FloatField()
    cost_price = forms.FloatField()
    selling_price = forms.FloatField()

class LaminatesAddForm(forms.Form):
    brand = forms.CharField()
    dimention = forms.CharField()
    Thickness = forms.IntegerField()
    series = forms.CharField()
    img1 = forms.ImageField(required=False)
    img2 = forms.ImageField(required=False)
    compcode = forms.CharField(required=False)
    description = forms.CharField(required=False)
    original_price = forms.FloatField()
    cost_price = forms.FloatField()
    selling_price = forms.FloatField()
    dim = forms.CharField()
    finish = forms.CharField()

class AdhesiveAdd(forms.Form):
    brand = forms.CharField()
    quantity = forms.CharField()
    application = forms.CharField()
    series = forms.CharField()
    img1 = forms.ImageField(required=False)
    img2 = forms.ImageField(required=False)
    compcode = forms.CharField(required=False)
    description = forms.CharField(required=False)
    original_price = forms.FloatField()
    cost_price = forms.FloatField()
    selling_price = forms.FloatField()


class SearchForm(forms.Form):
    category=forms.CharField()
    search=forms.CharField(required=False)

class OrderForm(forms.Form):
    productID=forms.CharField()

class Cart(forms.Form):
    quantity=forms.CharField()
    productID=forms.CharField()

class DeleteProductForm(forms.Form):
    product=forms.CharField()

gbstore/templates/gbstore/adhesiveorder.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
<head>

    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{% static 'customers/img/favicon.png' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Adhesive - GharBanao Store</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'gbstore/css/template.css' %}">
    <link rel="stylesheet" href="{% static 'gbstore/css/plyorder.css' %}">

</head>
<body>
<div class="row" style="height: 20px; background: #d8d8d8">

</div>
<nav class="navbar navbar-default">
    <div class="container-fluid">

        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'gbstore:index' %}" ><img src="{% static 'customers/img/GharBanaoLogo_nav.png' %}"></a>
        </div>

        <div id="search">
            <form method="get" action="{% url 'gbstore:ref' %}">
                <select name="category">
                    <option> All </option>
                    <option> Plywood </option>
                    <option> Laminates </option>
                    <option> Adhesives </option>
                </select>
                <input style="margin-left: -4px;" type="text" name="search" placeholder="Search by product name">
                <button style="margin-left: -4px;" class="btn" type="submit"><span class="glyphicon glyphicon-search"></span> <span class="hide-text" > Search </span></button>
            </form>
        </div>
        <div class="nav-btns">
            <ul class="h-list">
                <li class="btn"> <span class="glyphicon glyphicon-shopping-cart"></span> <span class="hide-text"> Cart </span></li>
                <li class="btn">  <span class="glyphicon glyphicon-user"></span> <span class="hide-text"> Profile </span><span style="font-size: 10px;" class="glyphicon glyphicon-chevron-down"></span> </li>
            </ul>
        </div>
</nav>
<div class="container-fluid page" id="page">

        <div class="row searchwin">
            <h4 align="center"  style="color: #5879b5">Search and place order for adhesives by brand and series e.g. Fevicol Pro Bond</h4>
            <div class="col-sm-3"></div>
            <div class="col-sm-3">
                <span style="color: #eee" class="glyphicon glyphicon-tag"></span>
                <input class="searchf" type="text" placeholder="Enter brand">

            </div>
            <div class="col-sm-3">
                <span style="color: #eee" class="glyphicon glyphicon-arrow-right"></span>
                <input class="searchf" type="text" placeholder="Enter series">

            </div>
            <div class="col-sm-3"></div>
        </div>

    <br>

        <div class="row nomargin">
            <center>
                <div class="row thick">
                    <h3>Available Denominations:</h3>
                    <button class="btn"> 1kg </button>
                    <button class="btn"> 2kg </button>
                    <button class="btn"> 5kg </button>
                    <button class="btn"> 10kg </button>
                    <button class="btn"> 20kg </button>
                    <button class="btn"> 30kg </button>
                    <button class="btn"> 50kg </button>
                </div>
                <br>
                <button class="btn">Submit</button>
            </center>
        </div>


</div>
</body>
</html>

gbstore/templates/gbstore/cart.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
<head>

    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{% static 'customers/img/favicon.png' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cart - GharBanao Store</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'gbstore/css/template.css' %}">
    <link rel="stylesheet" href="{% static 'gbstore/css/cart.css' %}">
    <script  src="{% static 'gbstore/js/noalert.js' %}"></script>

</head>
<body>
<div class="row" style="height: 20px; background: #d8d8d8">

</div>
<nav class="navbar navbar-default">
    <div class="container-fluid">

        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'gbstore:index' %}" ><img src="{% static 'customers/img/GharBanaoLogo_nav.png' %}"></a>
        </div>


        <div class="nav-btns">
            <ul class="h-list">
                <a href="{% url 'gbstore:mycart' %}"> <li class="btn"> <span class="glyphicon glyphicon-shopping-cart"></span> <span class="hide-text"> Cart  <b> {% if count %} ({{count}}) {%endif%}</b> </span></li></a>
                <a href="{% url 'designers:index' %}"><li class="btn">  <span class="glyphicon glyphicon-user"></span> <span class="hide-text"> Profile </span> </li></a>
            </ul>



        </div>
</nav>
<div class="container-fluid page" id="page">
    <center>
        <div align="left" class="win">
            <h3 class="gbcolor">Your Cart</h3>
            <hr class="hrcolor">
            {% if products %}
            {% for x in products %}

            <div class="row">
                <div class="item-img">
                    <img class="img-responsive" src="{% static 'gbstore/img/placeholder.png' %}">
                </div>
                <div class="col-xs-6 item-details">
                    <div class="col-sm-6">
                        <h4>{{x.0.brand}} {{x.0.series}} </h4>

                        {% if x.0.dimention %}
                        <h5>Size: {{x.0.dimention}}</h5>
                        {% endif %}

                        {% if x.0.Thickness %}
                        <h5>Thickness: {{x.0.Thickness}}</h5>
                        {% endif %}

                        {% if x.0.finish %}
                        <h5>Finish: {{x.0.finish}}</h5>
                        {% endif %}

                        {% if x.0.appication %}
                        <h5>Application: {{x.0.appication}}</h5>
                        {% endif %}

                        {% if x.0.quantity %}
                        <h5>Quantity: {{x.0.quantity}}</h5>
                        {% endif %}
                    </div>
                    <div class="col-sm-3">
                        <h4 class="no-margin">Qty:</h4>

                        <span class="">{{x.1}}</span>

                    </div>
                    <div class="col-sm-3">

                        <form action="{% url 'gbstore:delete_product' %}" method="post">
                            {% csrf_token %}
                            <button style="float: right; background: none; color: #123c88" type="submit" name="product" value="{{x.0.gbcode}}"><span class="glyphicon glyphicon-remove"></span> </button>
                        </form>
                        <h4 class="no-margin">Price:</h4>
                        <h3 class="price">₹{{x.0.selling_price}} × {{x.1}}</h3>
                    </div>
                </div>
            </div>
            <hr class="hrcolor">
            {% endfor %}

            <div class="row">
                <div class="item-img">
                    <h3>Total :</h3>
                </div>
                <div class="col-xs-6 item-details">
                    <div class="col-sm-9 ">

                    </div>
                    <div class="col-sm-3">

                        <h3>₹{{total}}</h3>
                    </div>
                </div>
            </div>
            <hr class="hrcolor">
            <div class="row">
                <div class="col-xs-12">
                    <form method="get"  action="{% url 'gbstore:deletecart' %}">
                        <button class="btn cntn-btn" type="submit">Clear Cart</button>
                    </form>

                    <form method="post" action="{% url 'gbstore:place_order' %}">
                        {% csrf_token %}
                        <button class="btn sbmt-btn" type="submit">Place order</button>
                    </form>
                </div>
            </div>
            {% else %}
            <br>
            <br>

            <center>
                <h3>Your cart is empty.</h3>
                Go to the homepage to start shopping
            </center>

            <br>
            <br>
            <br>
            <hr class="hrcolor">
            {% endif %}
            <br>
        </div>
    </center>

</div>
<script src="{% static 'customers/js/jquery.min.js' %}"></script>
<script src="{% static 'customers/js/bootstrap.min.js' %}"></script>
</body>
</html>

gbstore/templates/gbstore/mycart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My cart</title>
</head>
<body>
{% for x in products %}
    {{x.0.series}}
    {{x.0.selling_price}}
    {{x.1}}
    <form action="{% url 'gbstore:delete_product' %}" method="post">
        {% csrf_token %}
        <button type="submit" name="product" value="{{x.gbcode}}">Delete</button>
    </form>
<br>
{% endfor %}
<h1>
    Total : {{total}}
</h1>
</body>
<form method="get"  action="{% url 'gbstore:deletecart' %}">
    <button type="submit">Clear Cart</button>
</form>
<form method="post" action="{% url 'gbstore:place_order' %}">
    {% csrf_token %}
    <button type="submit">Place order</button>
</form>
</html>

gbstore/templates/gbstore/mycart1.html
<!DOCTYPE html>

<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>My cart</title>
    <script  src="{% static 'gbstore/js/noalert.js' %}"></script>
</head>
<body>
{% if products %}

{% for x in products %}

    {{x.0.series}}
    {{x.0.selling_price}}
    quantity:{{x.1}}
    <form action="{% url 'gbstore:delete_product' %}" method="post">
        {% csrf_token %}
        <button type="submit" name="product" value="{{x.0.gbcode}}">Delete</button>
    </form>
<br>
{% endfor %}
<h1>
    Total : {{total}}
</h1>
</body>
<form method="get"  action="{% url 'gbstore:deletecart' %}">
    <button type="submit">Clear Cart</button>
</form>
<form method="post" action="{% url 'gbstore:place_order' %}">
    {% csrf_token %}
    <button type="submit">Place order</button>
</form>
{% else %}
    <h1>No items in cart</h1>
{% endif %}
</body>
</html>

gbstore/templates/gbstore/shipping_details.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{% static 'customers/img/favicon.png' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Plywood - GharBanao Store</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'gbstore/css/template.css' %}">
    <script src="{% static 'customers/js/jquery.min.js' %}"></script>
    <script src="{% static 'customers/js/bootstrap.min.js' %}"></script>

</head>
<body>
<div class="row" style="height: 20px; background: #d8d8d8">

</div>
<nav class="navbar navbar-default">
    <div class="container-fluid">

        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'gbstore:index' %}" ><img src="{% static 'customers/img/GharBanaoLogo_nav.png' %}"></a>
        </div>


        <div class="nav-btns">
            <ul class="h-list">
                <a href="{% url 'gbstore:mycart' %}"> <li class="btn"> <span class="glyphicon glyphicon-shopping-cart"></span> <span class="hide-text"> Cart  <b> {% if count %} ({{count}}) {%endif%}</b> </span></li></a>
                <li class="btn"> <span class="glyphicon glyphicon-user"></span> <span class="hide-text"> Profile </span><span style="font-size: 10px;" class="glyphicon glyphicon-chevron-down"></span> </li>
            </ul>
        </div>
</nav>
<div class="container-fluid page" id="page">
    <center>
        <h4>Enter shipping details</h4>
        <form method="get" action="">
            <input type="text" name="" placeholder="Full name" style="width: 240px; padding: 5px 15px"><br><br>
            <textarea type="text" name="" placeholder="Address" style="width: 240px; height: 100px; padding: 5px 15px; resize: none"></textarea><br><br>
            <input type="text" name="" placeholder="Phone no." style="width: 240px; padding: 5px 15px"><br><br>
            <button class="btn btn-info" type="submit">Submit</button>

        </form>
    </center>
</div>


</body>

gbstore/templates/gbstore/view_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{p.gbcode}}</title>
</head>
<body>
     <div>
            <h3>{{p.brand}} {{p.series}} {{p.gbcode}}</h3>
            <h5>{{p.description}}</h5>
            <h5>{{p.dimention}}</h5>
            <form method="get" action="{% url 'gbstore:quantity' %}">
                <button type="submit" name="productID" value="{{p.gbcode}}">Order</button>
            </form>
        </div>
</body>
</body>
</html>